WITH 2021_USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM 2021_USERS),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM 2021_USERS)
GROUP BY 1,2
ORDER BY 1,2

