WITH REPLE AS
(
    SELECT RE.MEMBER_ID AS MEMBER_ID,COUNT(RE.MEMBER_ID) AS COUNT
    FROM REST_REVIEW RE
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1
)

SELECT P.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R USING(MEMBER_ID)
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID FROM REPLE)
ORDER BY REVIEW_DATE ASC,REVIEW_TEXT ASC